# Generated by Django 5.0.2 on 2024-03-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='article_images/')),
                ('price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
